<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use App\Models\UserAddress;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    public function definition(): array
    {
        return [
            'name' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
            'password' => Hash::make('password'),
            'contact_number' => $this->faker->phoneNumber(),
            'email_verified_at' => now(),
            'remember_token' => Str::random(10),
            'type' => 'customer', // default type
        ];
    }

    public function admin()
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'admin',
            'name' => 'Admin',
            'email' => 'admin@admin.com',
            'password' => Hash::make('12345678'),
            'email_verified_at' => null, // Not automatically verified - must update credentials
            'is_default' => true, // Default account created by seeder
        ]);
    }

    public function customer()
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'customer',
            'name' => $this->faker->name(),
            'email' => 'customer@customer.com',
            'password' => Hash::make('12345678'),
            'email_verified_at' => null, // Not automatically verified - must update credentials
            'is_default' => true, // Default account created by seeder
        ])->afterCreating(function ($user) {
            // Create a default address for the customer
                UserAddress::create([
                    'user_id' => $user->id,
                    'street' => $this->faker->streetAddress(),
                    'barangay' => 'Sala',
                    'city' => 'Cabuyao',
                    'province' => 'Laguna',
                    'is_active' => true,
                ]);
        });
    }

    public function member()
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'member',
            'name' => $this->faker->name(),
            'email' => null, // No email for members - they use member_id for login
            'contact_number' => $this->faker->unique()->phoneNumber(),
            'registration_date' => $this->faker->dateTimeThisYear(),
            'document' => $this->faker->imageUrl(640, 480, 'member', true),
            'password' => Hash::make('password'),
            'email_verified_at' => now(), // Automatically verify email for members
            'is_default' => true, // Default account created by seeder
            // member_id will be auto-generated by the User model's booted() method
        ])->afterCreating(function ($user) {
            // Create a default address for the member in user_addresses table
                UserAddress::create([
                    'user_id' => $user->id,
                    'street' => $this->faker->streetAddress(),
                    'barangay' => 'Sala',
                    'city' => 'Cabuyao',
                    'province' => 'Laguna',
                    'is_active' => true,
                ]);
        });
    }

    public function logistic()
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'logistic',
            'name' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
            'contact_number' => $this->faker->unique()->phoneNumber(),
            'registration_date' => $this->faker->dateTimeThisYear(),
            'password' => Hash::make('password'),
            'email_verified_at' => null, // Not automatically verified - must update credentials
            'is_default' => true, // Default account created by seeder
        ])->afterCreating(function ($user) {
            // Create a default address for the logistic
                UserAddress::create([
                    'user_id' => $user->id,
                    'street' => $this->faker->streetAddress(),
                    'barangay' => 'Sala',
                    'city' => 'Cabuyao',
                    'province' => 'Laguna',
                    'is_active' => true,
                ]);
        });
    }

    public function staff()
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'staff',
            'name' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
            'password' => Hash::make('password'),
            'email_verified_at' => null, // Not automatically verified - must update credentials
            'is_default' => true, // Default account created by seeder
        ]);
    }

    /**
     * Indicate that the model's email address is not verified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
} 