<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\PasswordChangeRequest;
use App\Notifications\MembershipUpdateNotification;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Illuminate\Support\Facades\Response;
use Barryvdh\DomPDF\Facade\Pdf;

class MembershipController extends Controller
{
    public function index()
    {
        $members = User::where('type', 'member')
            ->with('defaultAddress')
            ->get();
        
        // Get pending password change requests
        $pendingPasswordRequests = PasswordChangeRequest::with(['member', 'approvedBy'])
            ->where('status', 'pending')
            ->orderBy('requested_at', 'desc')
            ->get();
        
        return Inertia::render('Admin/Membership/index', [
            'members' => $members,
            'pendingPasswordRequests' => $pendingPasswordRequests
        ]);
    }

    public function add()
    {
        return Inertia::render('Admin/Membership/add', []);
    }

    public function store(Request $request)
    {
        // Validate the request data
        $request->validate([
            'name' => 'required|string|max:255',
            'password' => ['required', 'string', 'min:8', 'regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/'],
            'contact_number' => [
                'required',
                'numeric',
                'unique:users,contact_number',
                'regex:/^(\+639|09)\d{9}$/',
            ],
            'registration_date' => 'nullable|date',
            'document' => 'required|file|mimes:jpg,jpeg,png,pdf|max:2048',
            'street' => 'required|string|max:255',
            'barangay' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'province' => 'required|string|max:255',
        ]);

        if ($request->file('document')) {
            $image = $request->file('document');
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images/documents/'), $imageName);
            
            $member = User::create([
                'name' => $request->input('name'),
                'email' => null, // Email not required for members - they use member_id for login
                'password' => bcrypt($request->input('password')),
                'contact_number' => $request->input('contact_number'),
                'registration_date' => $request->input('registration_date', now()),
                'document' => 'images/documents/' . $imageName,
                'type' => 'member',
                // member_id will be auto-generated by the User model's booted() method
                'email_verified_at' => now(), // Automatically verify email
            ]);

            // Create address
            $member->userAddresses()->create([
                'street' => $request->input('street'),
                'barangay' => $request->input('barangay'),
                'city' => $request->input('city'),
                'province' => $request->input('province'),
                'is_active' => true,
            ]);

            // Notify admin and staff about membership update
            $adminUsers = \App\Models\User::whereIn('type', ['admin', 'staff'])->get();
            foreach ($adminUsers as $admin) {
                $admin->notify(new MembershipUpdateNotification($member, 'added'));
            }
        }

        return redirect()->route('membership.index')->with('message', 'Member added successfully');
    }

    public function edit($id)
    {
        $member = User::where('type', 'member')
            ->with('defaultAddress')
            ->findOrFail($id);
        return Inertia::render('Admin/Membership/edit', compact('member'));
    }

    public function update(Request $request, $id)
    {
        $member = User::where('type', 'member')->findOrFail($id);
        
        // Validate the request data
        $request->validate([
            'name' => 'required|string|max:255',
            'contact_number' => [
                'required',
                'numeric',
                'unique:users,contact_number,' . $id,
                'regex:/^(\+639|09)\d{9}$/',
            ],
            'registration_date' => 'nullable|date',
            'document' => 'nullable|file|mimes:jpg,jpeg,png,pdf|max:2048',
            'member_id' => 'nullable|string|unique:users,member_id,' . $id,
            'street' => 'required|string|max:255',
            'barangay' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'province' => 'required|string|max:255',
        ]);

        // Check if document is marked for deletion but no new file is uploaded
        if ($member->document_marked_for_deletion && !$request->file('document')) {
            return back()->withErrors([
                'document' => 'A new document must be uploaded to replace the one marked for deletion.'
            ]);
        }
        $member->update([
            'name' => $request->input('name'),
            'contact_number' => $request->input('contact_number'),
            'registration_date' => $request->input('registration_date') ?? now(),
            'member_id' => $request->input('member_id'),
        ]);

        // Update or create address
        $defaultAddress = $member->defaultAddress;
        if ($defaultAddress) {
            $defaultAddress->update([
                'street' => $request->input('street'),
                'barangay' => $request->input('barangay'),
                'city' => $request->input('city'),
                'province' => $request->input('province'),
            ]);
        } else {
            $member->userAddresses()->create([
                'street' => $request->input('street'),
                'barangay' => $request->input('barangay'),
                'city' => $request->input('city'),
                'province' => $request->input('province'),
                'is_active' => true,
            ]);
        }
        
        if ($request->file('document')) {
            // Delete old file if it was marked for deletion
            if ($member->document_marked_for_deletion && $member->document && file_exists(public_path($member->document))) {
                unlink(public_path($member->document));
            }
            
            $image = $request->file('document');
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images/documents'), $imageName);
            
            $member->document = 'images/documents/' . $imageName;
            $member->document_marked_for_deletion = false; // Reset the flag
        }

        $member->save();

        // Notify admin and staff about membership update
        $adminUsers = \App\Models\User::whereIn('type', ['admin', 'staff'])->get();
        foreach ($adminUsers as $admin) {
            $admin->notify(new MembershipUpdateNotification($member, 'updated'));
        }

        return redirect()->route('membership.index')->with('message', 'Member Details updated successfully');
    }

    public function destroy($id)
    {
        // Delete the image file if it exists
        $member = User::where('type', 'member')->findOrFail($id);
        if ($member->document && file_exists(public_path($member->document))) {
            unlink(public_path($member->document));
        }

        // Notify admin and staff about membership update
        $adminUsers = \App\Models\User::whereIn('type', ['admin', 'staff'])->get();
        foreach ($adminUsers as $admin) {
            $admin->notify(new MembershipUpdateNotification($member, 'removed'));
        }
        
        $member->delete();
        return redirect()->route('membership.index')->with('message', 'Member removed successfully');
    }

    public function deleteDocument($id)
    {
        $member = User::where('type', 'member')->findOrFail($id);
        
        // Mark document for deletion instead of deleting immediately
        $member->update(['document_marked_for_deletion' => true]);
        
        // Notify admin and staff about document marked for deletion
        $adminUsers = \App\Models\User::whereIn('type', ['admin', 'staff'])->get();
        foreach ($adminUsers as $admin) {
            $admin->notify(new MembershipUpdateNotification($member, 'document_marked_for_deletion'));
        }
        
        return response()->json([
            'success' => true,
            'message' => 'Document marked for deletion. Upload a new file to complete the process.'
        ]);
    }

    public function generateReport(Request $request)
    {
        $startDate = $request->get('start_date');
        $endDate = $request->get('end_date');
        $format = $request->get('format', 'view'); // view, csv, pdf
        $display = $request->get('display', false); // true for display mode

        $query = User::where('type', 'member');

        // Filter by registration date range
        if ($startDate) {
            $query->whereDate('registration_date', '>=', $startDate);
        }
        if ($endDate) {
            $query->whereDate('registration_date', '<=', $endDate);
        }

        $members = $query->orderBy('created_at', 'desc')->get();

        // Calculate summary statistics
        $summary = [
            'total_members' => $members->count(),
            'active_members' => $members->where('email_verified_at', '!=', null)->count(),
            'pending_verification' => $members->where('email_verified_at', null)->count(),
            'recent_registrations' => $members->where('created_at', '>=', now()->subDays(30))->count(),
        ];

        // If export is requested
        if ($format === 'csv') {
            return $this->exportToCsv($members, $display);
        } elseif ($format === 'pdf') {
            return $this->exportToPdf($members, $display);
        }

        // Return view for display
        return Inertia::render('Admin/Membership/report', [
            'members' => $members,
            'summary' => $summary,
            'filters' => [
                'start_date' => $startDate,
                'end_date' => $endDate,
            ],
        ]);
    }

    private function exportToCsv($members, $display = false)
    {
        $filename = 'membership_report_' . date('Y-m-d_H-i-s') . '.csv';
        
        if ($display) {
            // For display mode, return as plain text to show in browser
            $headers = [
                'Content-Type' => 'text/plain',
                'Content-Disposition' => 'inline; filename="' . $filename . '"',
            ];
        } else {
            // For download mode, return as CSV attachment
            $headers = [
                'Content-Type' => 'text/csv',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            ];
        }

        $callback = function() use ($members) {
            $file = fopen('php://output', 'w');
            
            // Write headers
            fputcsv($file, [
                'ID',
                'Name',
                'Email',
                'Contact Number',
                'Address',
                'Registration Date',
                'Email Verified',
                'Created Date'
            ]);

            // Write members data
            foreach ($members as $member) {
                fputcsv($file, [
                    $member->id,
                    $member->name,
                    $member->email,
                    $member->contact_number ?? 'N/A',
                    'N/A', // Address moved to user_addresses table
                    $member->registration_date ? $member->registration_date->format('Y-m-d') : 'N/A',
                    $member->email_verified_at ? 'Yes' : 'No',
                    $member->created_at->format('Y-m-d H:i:s')
                ]);
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    private function exportToPdf($members, $display = false)
    {
        $html = view('reports.membership-pdf', [
            'members' => $members,
            'generated_at' => now()->format('Y-m-d H:i:s')
        ])->render();

        $pdf = Pdf::loadHTML($html);
        $pdf->setPaper('A4', 'landscape');
        
        $filename = 'membership_report_' . date('Y-m-d_H-i-s') . '.pdf';
        
        return $display ? $pdf->stream($filename) : $pdf->download($filename);
    }

    /**
     * Approve a password change request
     */
    public function approvePasswordChange(Request $request, $requestId)
    {
        $passwordChangeRequest = PasswordChangeRequest::findOrFail($requestId);
        
        if ($passwordChangeRequest->status !== 'pending') {
            return back()->with('error', 'This request has already been processed.');
        }

        $passwordChangeRequest->update([
            'status' => 'approved',
            'approved_at' => now(),
            'approved_by' => $request->user()->id,
        ]);

        return back()->with('message', 'Password change request approved successfully. The member can now change their password.');
    }

    /**
     * Reject a password change request
     */
    public function rejectPasswordChange(Request $request, $requestId)
    {
        $passwordChangeRequest = PasswordChangeRequest::findOrFail($requestId);
        
        if ($passwordChangeRequest->status !== 'pending') {
            return back()->with('error', 'This request has already been processed.');
        }

        $passwordChangeRequest->update([
            'status' => 'rejected',
            'approved_at' => now(),
            'approved_by' => $request->user()->id,
        ]);

        return back()->with('message', 'Password change request rejected.');
    }
}
